/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: valeriydeyneca (https://sketchfab.com/valeriydeyneca)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/folders-ca754d09e0ae42fdaf21b7c185f3a8cc
title: Folders
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame} from "@react-three/fiber";

export function Folders(props) {
  const { nodes, materials } = useGLTF('/folders.gltf')
  const folderRefOne = useRef()
  const folderRefTwo= useRef()

  useFrame(({clock}) => {
    const elapsedTime = clock.getElapsedTime()

    folderRefOne.current.rotation.z = elapsedTime / 3;
    folderRefTwo.current.rotation.z = (elapsedTime / 3.);
  })
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.1}>
          <group position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={130}>
            <mesh ref={folderRefOne}geometry={nodes.Folder_UV1__0.geometry} material={materials['Scene_-_Root']} />
          </group>
          <group position={[15, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={130}>
            <mesh ref={folderRefTwo} geometry={nodes.Folder_UV2__0.geometry} material={materials['Scene_-_Root']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/folders.gltf')
