/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: basti_931 (https://sketchfab.com/basti_931)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/house-low-poly-3f2431b6c0a8440a87ec0fb1f40798e2
title: House_Low Poly
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function House3D(props) {
  const { nodes, materials } = useGLTF("/house3D.gltf");

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0.5]}>
        <group position={[-30, 70, -50]} scale={1}>
          <mesh
            geometry={nodes.Object_3.geometry}
            material={materials.Material__23}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/house3D.gltf");
