/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Skript47 (https://sketchfab.com/Skript47)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/computer-monitor-169-low-poly-game-ready-336de680dd9a4d84943d05d9c7dde1b0
title: Computer Monitor 16:9 (Low Poly, Game Ready)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame} from "@react-three/fiber";

export function MonitorIcon(props) {
  const { nodes, materials } = useGLTF('/monitor.gltf')

  const monitorRef = useRef()
  

  useFrame(({clock}) => {
    const elapsedTime = clock.getElapsedTime()

    monitorRef.current.rotation.y = elapsedTime / 2;
  })
  return (
    <group {...props} dispose={null} ref={monitorRef}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={8} position={[0,-3,0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Monitor_01_A} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Monitor_01_B} />
      </group>
    </group>
  )
}

useGLTF.preload('/monitor.gltf')
